apiVersion: v1
kind: Service
metadata:
  name: vprodb # from application.properties -> jdbc.url=jdbc:mysql://vprodb:3306/
spec:
  ports:
    - port: 3306
      targetPort: vprodb-port # from vprodbdep.yaml ports/name
      protocol: TCP
  selector:
    app: vprodb # this is the label of the pod from vprodbdep.yaml metadata
  type: ClusterIP