apiVersion: v1
kind: Service
metadata:
  name: vprocache01 # from application.properties memcached.active.host=vprocache01
spec:
  ports:
    - port: 11211 # from application.properties memcached.active.port=11211
      targetPort: vpromc-port
      protocol: TCP
  selector:
    app: vpromc # the pod label from mcdep.yaml
  type: ClusterIP