apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
    - port: 15672
      targetPort: vpromq01-port # from rmq-dep.yaml ports/name
      protocol: TCP
  selector:
    app: vpromq01 # the label of the pod
  type: ClusterIP