apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: lendoo73/vprofiledb:latest
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data # from volumes/name
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret # from secret.yaml metadata/name
                  key: db-pass     # from secret.yaml data/
      nodeSelector:
        zone: eu-west-2a # the label we created in lesson 264.
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-05823eed402fc3f76 # from lesson 264. or from AWS console EC2 -> Elastic Block Store -> Volumes
            fsType: ext4
