apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: 80
      targetPort: vproapp-port # from vproappdep.yaml ports/name
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer